language: java

install: mvn install -DskipTests=true -Dgpg.skip=true

jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk7

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
