branches:
    only:
        - master

language: java

install: mvn install -DskipTests=true

jdk:
    - oraclejdk8
    - oraclejdk11
    - openjdk10
    - openjdk11

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
