dist: bionic

branches:
    only:
        - master

language: java

install: mvn install -DskipTests=true

jdk:
    - openjdk8
    - openjdk10
    - openjdk11
    - oraclejdk10
    - oraclejdk11

services:
    - xvfb
